apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prompt-proto-service
  namespace: prompt-proto-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/target-utilization-percentage: "80"
        # Update this field if `make apply` by itself doesn't make a new revision.
        revision: "32"
      creationTimestamp: null
    spec:
      containerConcurrency: 1
      containers:
      - image: ghcr.io/lsst-dm/prompt-proto-service:DM-38269-latest
        imagePullPolicy: Always
        name: user-container
        env:
        - name: RUBIN_INSTRUMENT
          value: LATISS
        - name: SKYMAP
          value: latiss_v1
        - name: PUBSUB_VERIFICATION_TOKEN
          value: rubin-prompt-proto-main
        - name: IMAGE_BUCKET
          value: rubin-summit
        - name: CALIB_REPO
          value: /app/butler
        - name: IP_APDB
          # Need explicit port for make_pgpass.py
          value: usdf-prompt-processing-dev.slac.stanford.edu:5432
        - name: DB_APDB
          value: lsst-devl
        - name: USER_APDB
          value: rubin
        - name: NAMESPACE_APDB
          value: pp_apdb
        - name: IP_REGISTRY
          # Need explicit port for make_pgpass.py
          value: usdf-butler.slac.stanford.edu:5432
        - name: DB_REGISTRY
          value: lsstdb1
        - name: USER_REGISTRY
          value: rubin
        - name: KAFKA_CLUSTER
          value: prompt-processing-kafka-bootstrap.kafka:9092
        - name: USER_REGISTRY
          value: rubin
        - name: PSQL_REGISTRY_PASS
          valueFrom:
            secretKeyRef:
              name: usdf-butler-creds
              key: password
        - name: PSQL_APDB_PASS
          valueFrom:
            secretKeyRef:
              name: usdf-prompt-processing-creds
              key: password
        - name: S3_ENDPOINT_URL
          value: https://s3dfrgw.slac.stanford.edu
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /app/s3/credentials
        - name: LOCAL_REPOS
          value: "/tmp-butler"
        volumeMounts:
          - mountPath: /app/s3/credentials
            name: s3-credentials-file
            subPath: credentials
          - mountPath: /tmp-butler
            name: ephemeral
            readOnly: false
          - mountPath: /app/butler/
            name: central-repo-file
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources:
          requests:
            ephemeral-storage: "8Gi"
          limits:
            ephemeral-storage: "14Gi"
      volumes:
      - name: s3-credentials-file
        secret:
          secretName: s3-temp
      - name: central-repo-file
        secret:
          secretName: central-repo-file3
      - name: ephemeral
        emptyDir:
          sizeLimit: "14Gi"
      enableServiceLinks: false
      imagePullSecrets:
      - name: regcred
      timeoutSeconds: 600